package ru.itpark;

import static ru.itpark.exerciseLesson1.ExerciseLesson1.Exercise1;
import static ru.itpark.exerciseLesson2.ExerciseLesson2.Exercise2;
import static ru.itpark.lesson1.Lesson1.Task1;
import static ru.itpark.lesson10.Lesson10.Task10;
import static ru.itpark.lesson11.Lesson11.Task11;
import static ru.itpark.lesson12.Lesson12.Task12;
import static ru.itpark.lesson13.Lesson13.Task13;
import static ru.itpark.lesson14.Lesson14.Task14;
import static ru.itpark.lesson15.Lesson15.Task15;
import static ru.itpark.lesson16.Lesson16.Task16;
import static ru.itpark.lesson17.Lesson17.Task17;
import static ru.itpark.lesson18.Lesson18.Task18;
import static ru.itpark.lesson19.Lesson19.Task19;
import static ru.itpark.lesson2.Lesson2.Task2;
import static ru.itpark.lesson20.Lesson20.Task20;
import static ru.itpark.lesson21.Lesson21.Task21;
import static ru.itpark.lesson22.Lesson22.Task22;
import static ru.itpark.lesson3.Lesson3.Task3;
import static ru.itpark.lesson4.Lesson4.Task4;
import static ru.itpark.lesson5.Lesson5.Task5;
import static ru.itpark.lesson6.Lesson6.Task6;
import static ru.itpark.lesson7.Lesson7.Task7;
import static ru.itpark.lesson8.Lesson8.Task8;
import static ru.itpark.lesson9.Lesson9.Task9;

public class Main {
    public static void main(String[] args) {

        System.out.println("Lesson 1:");
        Task1();
        System.out.println("\nLesson 2:");
        Task2();
        System.out.println("\nLesson 3:");
        Task3();
        System.out.println("\nLesson 4:");
        Task4();
        System.out.println("\nLesson 5:");
        Task5();
        System.out.println("\nLesson 6:");
        Task6();
        System.out.println("\nLesson 7:");
        Task7();
        System.out.println("\nLesson 8:");
        Task8();
        System.out.println("\nLesson 9:");
        Task9();
        System.out.println("\nLesson 10:");
        Task10();
        System.out.println("\nLesson 11:");
        Task11();
        System.out.println("\nLesson 12:");
        Task12();
        System.out.println("\nLesson 13:");
        Task13();
        System.out.println("\nLesson 14:");
        Task14();
        System.out.println("\nLesson 15:");
        Task15();
        System.out.println("\nLesson 16:");
        Task16();
        System.out.println("\nLesson 17:");
        Task17();
        System.out.println("\nLesson 18:");
        Task18(4);
        System.out.println("\nLesson 19:");
        Task19();
        System.out.println("\nLesson 20:");
        Task20();
        System.out.println("\nLesson 21:");
        Task21();
        System.out.println("\nLesson 22:");
        Task22();
        System.out.println("\nExercise 1:");
        Exercise1();
        System.out.println("\nExercise 2:");
        Exercise2();
    }
}